version: '2'

services:
  db:
    image: mysql
    container_name: mysql
    env_file:
      - db.env
    environment:
      - MYSQL_ROOT_PASSWORD=groupe1
    networks:
      - nrph
    volumes:
      - db_volume:/var/lib/mysql

  redis:
    image: redis:7.0.4-alpine
    container_name: redis
    restart: always
    volumes:
      - redis_volume:/data
    networks:
      - nrph

  nextcloud:
    image: nextcloud
    container_name: nextcloud
    restart: always
    volumes:
      - nextcloud_volume:/var/www/html
    environment:
      - MYSQL_HOST=db
      - REDIS_HOST=redis
    env_file:
      - db.env
    expose:
      - '80'
    networks:
      - nrph

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./ssl-proxy:/etc/nginx/ssl
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - db
      - redis
      - nextcloud
    networks:
      - nrph

# nextcloud-reversed-proxy-http
networks:
  nrph:
    driver: bridge

volumes:
  redis_volume:
  db_volume:
  nextcloud_volume:
